apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-login
  template:
    metadata:
      labels:
        app: backend-login
    spec:
      containers:
        - name: backend-login
          image: nithi1230/quiz-backend-login:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
